CREATE TABLE IF NOT EXISTS "vehicle_position"(
  "id" serial NOT NULL,
  "desi" text,
  "dir" text,
  "oper" numeric,
  "veh" numeric,
  "tst" timestamp,
  "tsi" timestamp,
  "spd" numeric,
  "hdg" numeric,
  "lat" numeric,
  "long" numeric,
  "acc" numeric,
  "dl" numeric,
  "odo" numeric,
  "drst" numeric,
  "oday" date,
  "jrn" numeric,
  "line" numeric,
  "start" text,
  "loc" text,
  "stop" text,
  "route" text,
  "occu" numeric,
  "created_at" timestamp,
  "updated_at" timestamp
);

