import { numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const vehiclePosition = pgTable('vehicle_position', {
  id: serial('id'),
  desi: text('desi'),
  dir: text('dir'),
  oper: numeric('oper'),
  veh: numeric('veh'),
  tst: timestamp('tst'),
  tsi: timestamp('tsi'),
  spd: numeric('spd'),
  hdg: numeric('hdg'),
  lat: numeric('lat'),
  long: numeric('long'),
  acc: numeric('acc'),
  dl: numeric('dl'),
  odo: numeric('odo'),
  drst: numeric('drst'),
  oday: text('oday'),
  jrn: numeric('jrn'),
  line: numeric('line'),
  start: text('start'),
  loc: text('loc'),
  stop: text('stop'),
  route: text('route'),
  occu: numeric('occu'),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});
